language: php

before_script:
    - sudo chmod 777 build.sh
before_install:
  - mysql -e 'CREATE DATABASE myapp_test;'
  - sudo apt-get install phpunit
  - composer self-update
  - composer install
services:
  - mysql
script:
  - ./build.sh
